// Code generated by "stringer -type=Type"; DO NOT EDIT.

package restrictions

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Invalid-0]
	_ = x[Domain-1]
	_ = x[Application-2]
	_ = x[TypeEnd-3]
}

const _Type_name = "InvalidDomainApplicationTypeEnd"

var _Type_index = [...]uint8{0, 7, 13, 24, 31}

func (i Type) String() string {
	if i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
